on:
    push:
        branches:
            - master
        tags-ignore:
            - '**'
    pull_request:
        branches:
            - '**'

name: Build and Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 17
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install
        run: yarn install --ignore-scripts

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test
